# CONFIGURATION FILE 
# All paths are to be given without final slash.

# Paths
# -----
paths: 
  # In:
  flow: /path/to/flow/directory
  mesh: /path/to/mesh/directory
  observations: /path/to/observations/directory 
  # Out:
  results: /path/to/results/directory
  samples: /path/to/samples/directory
  model: /path/to/model/directory

# Name
# ----
name: afrl_scramjet

# Geometry
# --------
geometry:
  dimension: 2

# Random number generation
# ------------------------
seed: 1234

# Files
# -----
files:
  flowfield: flow.vtu        # Must be a vtk file
  mesh: afrl2d.geo           # Must be a gmsh file
  model_name: my_model

# Run setup
# ---------
run:
  model: pinn                # Options: supervised or pinn
  equation: euler            # Options: euler or rans
  device: cpu                # Options: cpu or cuda
  problem: inverse           # Options: forward or inverse

  routines:
    sampling: true
    postprocessing: true

  checkpoint:
    load_model: false
    save_model: false

  verbose: true

# Identification problem
# ----------------------
identification:

  observations:
    
    schlieren: 
      enabled: true
      grad_type: grad_x      # Options: grad_x, grad_y, magnitude
      density_name: Density  # Density name form CFD framework
      
      image:
        resolution: [512, 128]        # width, height
        supersampling: 2

      rendering:
        blur_sigma_pixels: 0.8
        normalization_percentile: 99.0

      noise:
        type: gaussian       # Options: none, gaussian
        level: 0.01          # 0.01 means 1% noise

      sampling:
        points: 4096
        uniform_fraction: 0.70
        alpha: 1.0

    velocity_profiles:
      enabled: true
      filename: velocity_profile   # Must be a csv file. velocity_profile_u_3.csv
      n_files: 8

    pressure_taps:
      enabled: true
      filename: pressure_taps      # Must be a csv file.

# Neural network
# --------------
network:
  architecture: gnn          # Options: mlp or gnn 

  mlp:
    layers: [2, 32, 32, 32, 4] 
    activation: tanh         # Options: tanh, sigmoid, sin, softplus, silu/swish or gelu

    dropout:
      probability: 0.0
      hidden_layer_indices: [1, 2]

  gnn:
    latent_dim: 8
    activation: tanh         # Options: tanh, sigmoid, sin, softplus, silu/swish or gelu
    neighbors: 4             

    attributes:
      node:
        boundary_marker: false # TODO 
        
      edge:
        squared_distance: true                

    processor:
      message_layers: 2  
      aggregation: sum       # Options: sum, max or mean
      residual: true

# Sampling
# --------
sampling:
  method: lhs                # Options: random or lhs

  boundaries:
    names:
      - inlet
      - bottom
      - outlet
      - top

  data_points:
    interior: 2100
    gradient: 2300
    boundary: [40, 260, 40, 160]

  collocation_points:
    interior: 1700
    gradient: 1700
    boundary: [40, 260, 40, 160]

  gradient_sampling:
    variable: Density
    pool_factor: 8
    alpha: 1.4

# Dataset split [percentage %]
# ----------------------------
dataset:
  p_training_data: 80
  p_validation_data: 10
  p_test_data: 10

# Optimizers
# ----------
optimizer:
  adam:
    enabled: true
    iterations: 8
    learning_rate: 4.0e-4

    scheduler:
      step_size: 2000
      gamma: 0.8

  # lbfgs starts after adam optimizer finishes
  # if both are enabled.
  lbfgs:
    enabled: true
    iterations: 4
    learning_rate: 1.0
    max_iter_per_step: 30

# Loss
# ----
loss:
  print_frequency: 1

  weights:
    data:
      rho: 1.0
      u: 1.0
      v: 200.0
      p: 4.0
      mut: 1.0

    residual:
      f1: 1.0
      f2: 1.0
      f3: 1.0
      f4: 1.0

# Physical parameters
# -------------------
physics:
  gas:
    gamma: 1.4        # Heat capacity ratio
    R: 287.058        # J/(kg K) - Universal gas constant

  reference:
    Lref: 0.0254      # m
    U_0: 727.0        # m/s
    rho: 0.657        # kg/m^3
    mu: 1.97e-5       # N s / m^2 - Dynamic viscosity - freestream

  turbulence:
    Pr: 0.72          # Laminar Prandtl number
    Prt: 0.9          # Turbulent Prandtl number

  sutherland:
    T0: 273.15        # K
    mu0: 1.716e-5     # N s / m^2
    S: 110.4          # K

# Post processing 
# ---------------
post_processing:
  error_type: abs_error_01  # Options: abs_error_01

  fields: # from CFD
    - Density
    - Pressure
    - Velocity
    - Velocity
    #- Eddy_Viscosity

  latex:
    - $\rho$ $[kg/m^{3}]$
    - $p$ $[Pa]$
    - $u$ $[m/s]$
    - $v$ $[m/s]$
    #- $\hat{\mu}_{t}$ $[kg/m \cdot s]$ 

  components: [0, 0, 0, 1] #, 0

  colormaps:
    - bwr
    - bwr
    - bwr
    - bwr
    #- bwr

  scales:
    - [0.0, 1.3]
    - [1.3e4, 1.67e5]
    - [-750.0, 950.0]
    - [-315.0, 315.0]
    #- [0.0,0.05]